# Generated by Django 4.2.1 on 2023-08-21 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('platesapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivatedNumberPlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberplate', models.CharField(max_length=20)),
                ('owner_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='DeletedNumberPlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberplate', models.CharField(max_length=20)),
                ('owner_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='PendingNumberPlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberplate', models.CharField(max_length=20)),
                ('owner_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberplate', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
