# Generated by Django 4.2.1 on 2023-08-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("platesapp", "0002_activatednumberplate_deletednumberplate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Activated", "Activated"),
                    ("Deleted", "Deleted"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
    ]
